services:
  postgres:
    container_name: postgres-sql-mess
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: mess_db
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - mess_network
    restart: unless-stopped
  keycloak:
    container_name: keycloak-mess
    image: quay.io/keycloak/keycloak:26.0.0
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - mess_network
    command:
      - "start-dev"

networks:
  mess_network:
    driver: bridge

volumes:
  postgres:
    driver: local